name 'generate_fix' is not defined
Traceback (most recent call last):
  File "/exp/dafny_repair/./src/generating_llm_fix.py", line 242, in process_method
    new_method, diff = test_prompt(
                       ^^^^^^^^^^^^
  File "/exp/dafny_repair/./src/generating_llm_fix.py", line 189, in test_prompt
    response = llm_prompt.get_fix(
               ^^^^^^^^^^^^^^^^^^^
  File "/exp/dafny_repair/./src/llm_prompt.py", line 128, in get_fix
    fix = generate_fix(self, model_parameters)
          ^^^^^^^^^^^^
NameError: name 'generate_fix' is not defined
